### ISSUE TITLE
_site should not be included in repo.

### ISSUE THREAD

**Issue by aatxe** [silcgroup/website#1]
As far as I can tell, the Travis setup will correctly build everything from a clean slate and sync it. We shouldn't need to be keeping _site in this repo, right?

**Comment by dbp** [comment]
Mmmm. Definitely true that it's not needed. And I guess it can be a (misleading) source of merge conflicts, so if you want to delete / .gitignore it no complaints from me. (I'm not sure why, but my habit has been to keep usable build artifacts in-tree, if only to make things more reproducible. But in this case we have an entire repository of build artifacts, so probably completely pointless).

**Comment by aatxe** [comment]
Okay, I've removed it in 97ec845bc8bf08ea1cdc809e1dadeea34c6a133d. Hopefully, this will avoid some future merge conflicts. ;)
