### ISSUE TITLE
Gabriel's website is Wrong

### ISSUE THREAD

**Issue by maxsnew** [silcgroup/website#3]
@gasche what website is right for you? Right now we have http://www.ccs.neu.edu/home/gasche/ but it looks like http://gallium.inria.fr/~scherer/ is more up-to-date. Is that your main webpage?

**Comment by gasche** [comment]
They should both be up-to-date (I'll fix my script), and I don't have a more up-to-date website than the northeastern one for now. I'll ping when I do have one.

**Comment by gasche** [comment]
PS: of course the only change from the stale-neu-webpage is the information you encouraged me to add. Thanks!

**Comment by gasche** [comment]
Apparently the `git` version on neu's login machine ( login.ccs.neu.edu ) *regressed* since last year, very odd...

**Comment by maxsnew** [comment]
So you want us to keep using the ccs one? I don't see why but ok

**Comment by gasche** [comment]
Well because there isn't a better one for now, and this one remains updated.
